openvpn.api/openvpn.api/Areas/Account/Controllers/ClientEventsController.cs
/*
    The MIT License (MIT)

    Copyright (c) 2014 Mehmetali Shaqiri (mehmetalishaqiri@gmail.com)

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE. 
 */


using System.Web.Mvc;

namespace openvpn.api.Areas.Account.Controllers
{
    public class ClientEventsController : Controller
    {
        // GET: Account/OpenVpnEvents
        public ActionResult Index()
        {
            return View();
        }
    }
}

openvpn.api/openvpn.api/Areas/Account/Controllers/DashboardController.cs
/*
    The MIT License (MIT)

    Copyright (c) 2014 Mehmetali Shaqiri (mehmetalishaqiri@gmail.com)

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE. 
 */

using System.Web.Mvc;
using openvpn.api.core.auth;

namespace openvpn.api.Areas.Account.Controllers
{
    [Guardian]
    public class DashboardController : Controller
    {
        // GET: Account/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

openvpn.api/openvpn.api/Areas/Account/Controllers/ProfileController.cs
/*
    The MIT License (MIT)

    Copyright (c) 2014 Mehmetali Shaqiri (mehmetalishaqiri@gmail.com)

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE. 
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace openvpn.api.Areas.Account.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Account/Profile
        public ActionResult Index()
        {
            var profile = Session["ExternalLoginModel"] as openvpn.api.core.auth.ExternalLoginModel;
            return View(profile);
        }


        public ActionResult Logout()
        {
            Session.Abandon();

            var ctx = Request.GetOwinContext();
            var authenticationManager = ctx.Authentication;
            authenticationManager.SignOut();


            return RedirectToAction("Index", "Home", new { area = "" });
        }
    }
}

openvpn.api/openvpn.api/Controllers/EventsController.cs
/*
    The MIT License (MIT)

    Copyright (c) 2014 Mehmetali Shaqiri (mehmetalishaqiri@gmail.com)

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE. 
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using openvpn.api.common.domain;
using openvpn.api.core;
using openvpn.api.core.controllers;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using openvpn.api.core.indexes;
using Raven.Abstractions.Indexing;
using Raven.Client;
using Raven.Client.Indexes;
using Raven.Client.Linq;
using openvpn.api.shared;

namespace openvpn.api.Controllers
{
    public class EventsController : RavenDbApiController
    {
        /// <summary>
        /// Store open vpn event in RavenDb document store.
        /// </summary>
        /// <param name="eventModel">The event model passed by open vpn client connect/disconnect</param>
        /// <returns></returns>
        public async Task<HttpResponseMessage> Post([FromBody]Event eventModel)
        {
            await Session.StoreAsync(eventModel);

            return new HttpResponseMessage(HttpStatusCode.Created);
        }


        /// <summary>
        /// Get all open vpn client events
        /// </summary>
        /// <returns>A collection of Event model</returns>
        [Route("api/events/clients/all")]
        public async Task<IEnumerable<Event>> GetAllClientEvents()
        {

            var query = Session.Query<Event>()
                    .Where(r => r.Type == EventType.Connect || r.Type == EventType.Disconnect)
                    .OrderByDescending(e => e.EnteredOn)
                    .ToListAsync();

            return await query;
        }


        /// <summary>
        /// Get open vpn client events for user certificates
        /// </summary>
        /// <param name="email">User's email address</param>
        /// <returns>A collection of Event model</returns>
        [Route("api/events/client/all/{email}")]
        public async Task<IEnumerable<Event>> GetUserEvents(string email)
        {
            var user = await Session.Query<User>().SingleOrDefaultAsync(u => u.Email == email);


            if (user == null)
                return null;

            var userCertificates = user.Certificates.Select(c => c.CommonName.ToLower()).ToArray();

            var query = Session.Query<Event>()
                    .Where(r => r.CommonName.In<string>(userCertificates) && (r.Type == EventType.Connect || r.Type == EventType.Disconnect))
                    .OrderByDescending(e => e.EnteredOn)
                    .ToListAsync();


            return await query;
        }


        /// <summary>
        /// Get open vpn client events for user certificates for today
        /// </summary>
        /// <param name="email">User's email address</param>
        /// <returns>A collection of Event model</returns>
        [Route("api/events/client/today/{email}")]
        public async Task<IEnumerable<Event>> GetTodaysEvents(string email)
        {
            var user = await Session.Query<User>().SingleOrDefaultAsync(u => u.Email == email);


            if (user == null)
                return null;

            var userCertificates = user.Certificates.Select(c => c.CommonName.ToLower()).ToArray();

            var query = Session.Query<Event>()
                    .Where(r => r.CommonName.In<string>(userCertificates) && r.EnteredOn.Date == DateTime.Now.Date && (r.Type == EventType.Connect || r.Type == EventType.Disconnect))
                    .OrderByDescending(e => e.EnteredOn)
                    .ToListAsync();

            return await query;
        }


        /// <summary>
        /// Get open vpn server events
        /// </summary>
        /// <returns>A collection of Event model</returns>
        [Route("api/events/server/all")]
        public async Task<IEnumerable<Event>> GetServerEvents()
        {
            var query = Session.Query<Event>()
                    .Where(r => r.Type == EventType.Up || r.Type == EventType.Down)
                    .OrderByDescending(e => e.EnteredOn)
                    .ToListAsync();
            return await query;
        }


        [Route("api/events/stats/all")]
        public async Task<NetworkFlowModel> GetEventStats()
        {
            var stats = await Session.Query<NetworkFlowReduceResult, NetworkFlowView>()
                .ToListAsync();

            return new NetworkFlowModel
            {
                Clients = stats.Select(e => e.CommonName).ToList(),
                Series = new List<ChartSerie>
                {
                    new ChartSerie { name = "Download", data = stats.Select(e => (float)(e.BytesReceived / 1024) / 1024).ToArray() },
                    new ChartSerie { name = "Upload", data = stats.Select(e => (float)(e.BytesSent / 1024) / 1024).ToArray() }
                }
            };
        }

        [Route("api/events/stats/{email}")]
        public async Task<NetworkFlowModel> GetEventStats(string email)
        {
            var user = await Session.Query<User>().SingleOrDefaultAsync(u => u.Email == email);

            if (user == null)
                return null;

            var userCertificates = user.Certificates.Select(c => c.CommonName.ToLower()).ToArray();

            var stats = await Session.Query<NetworkFlowReduceResult, NetworkFlowView>()
                .Where(r => r.CommonName.In<string>(userCertificates))
                .ToListAsync();

            return new NetworkFlowModel
            {
                Clients = stats.Select(e => e.CommonName).ToList(),
                Series = new List<ChartSerie>
                {
                    new ChartSerie { name = "Download", data = stats.Select(e => (float)(e.BytesReceived / 1024) / 1024).ToArray() },
                    new ChartSerie { name = "Upload", data = stats.Select(e => (float)(e.BytesSent / 1024) / 1024).ToArray() }
                }
            };
        }
    }
}

openvpn.api/openvpn.api/Controllers/UsersController.cs
/*
    The MIT License (MIT)

    Copyright (c) 2014 Mehmetali Shaqiri (mehmetalishaqiri@gmail.com)

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE. 
 */

using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using openvpn.api.common.domain;
using openvpn.api.core.controllers;
using openvpn.api.shared;
using Raven.Client;
using openvpn.api.core.auth;

namespace openvpn.api.Controllers
{
    public class UsersController : RavenDbApiController
    {

        /// <summary>
        /// Get requested user by email
        /// </summary>
        [Route("api/users/{email}")]
        public async Task<User> Get(string email)
        {
            return await Session.Query<User>().SingleOrDefaultAsync(u => u.Email == email);
        }

        /// <summary>
        /// Get all users
        /// </summary>
        [Route("api/users/all")]
        public async Task<IEnumerable<User>> Get()
        {
            var query = Session.Query<User>().OrderBy(u => u.Firstname).ToListAsync();

            return await query;
        }


        [HttpPost]
        public async Task<ApiStatusCode> Post([FromBody]User userModel)
        {
            var user = await Session.Query<User>().SingleOrDefaultAsync(u => u.Email == userModel.Email);

            if (ModelState.IsValid)
            {

                if (user != null)
                    return ApiStatusCode.Exists;

                await Session.StoreAsync(userModel);

                return ApiStatusCode.Saved;
            }
            return ApiStatusCode.Error;
        }

        [HttpDelete]
        [Route("api/users/{email}")]
        public async Task<ApiStatusCode> Delete(string email)
        {
            var user = await Session.Query<User>().SingleOrDefaultAsync(u => u.Email == email);

            if (user == null)
                return ApiStatusCode.Error;

            Session.Delete<User>(user);
            return ApiStatusCode.Deleted;
        }


        [HttpPut]
        public async Task<ApiStatusCode> Put(User userModel)
        {
            var user = await Session.Query<User>().SingleOrDefaultAsync(u => u.Email == userModel.Email);

            if (user != null)
            {
                user.Firstname = userModel.Firstname;
                user.Lastname = userModel.Lastname;

                user.Certificates = userModel.Certificates;

                await Session.SaveChangesAsync();

                return ApiStatusCode.Saved;
            }
            return ApiStatusCode.Error;
        }
    }
}

openvpn.api/openvpn.api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>OpenVpn Event Viewer | @ViewBag.Title</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/favicon.ico">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/jumbotron-narrow.css" rel="stylesheet">
    <link href="~/Content/style.css" rel="stylesheet" />
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="~/scripts/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="~/scripts/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <div class="container">
        <div class="header">
            <nav>
                @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { id = "login-form" }))
                {
                    <ul class="nav nav-pills pull-right">
                        <li role="presentation" class="active"><a href="#">Home</a></li>
                        <li role="presentation">
                            @Html.Hidden("loginIdentifier", "Google")
                            <a href="@Url.Action("Login","Home")" >Login with Google</a>


                        </li>
                    </ul>
                }
            </nav>
            <h3>OpenVPN Event Viewer</h3>
        </div>



        @RenderBody()

        <footer class="footer text-center">
            <p>&copy; Mehmetali Shaqiri (mehmetalishaqiri@gmail.com) 2014 &nbsp;|&nbsp; OpenVpn Event Viewer @VersionHtmlHelper.AppVersion()</p>
            <p><a id="forkme_banner" href="https://github.com/spartanbeg/OpenVPN-Event-Viewer">View on GitHub</a></p>
        </footer>

    </div> <!-- /container -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="~/scripts/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

openvpn.api/openvpn.api/Views/Shared/_Profile.cshtml
@using openvpn.api.common.domain
@{
    var session = HttpContext.Current.Session["ExternalLoginModel"] as openvpn.api.core.auth.ExternalLoginModel;

}

@if (session != null)
{
    <li><img src="@session.Picture" class="profileImage img-circle" /></li>
    <li>
        <a href="@session.Profile">

            @if (!String.IsNullOrEmpty(session.Name))
            {
                <text>@session.Name</text>
            }
            else
            {
                <text>@session.Email</text>
            }
        </a>
    </li>
}

openvpn.api/openvpn.api/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/favicon.ico">

    <title>OpenVpn Event Viewer | @ViewBag.Title</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/dashboard.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="~/scripts/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="~/scripts/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/images/logo.png" class="logo" />
                <a class="navbar-brand" href="@Url.Action("Index","Dashboard", new {area="Account"})">OpenVpn Event Viewer</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @Html.Partial("_Profile")
                    <li><a href="@Url.Action("Index", "Profile", new { area = "Account" })">Profile</a></li>
                    <li><a href="@Url.Action("Logout", "Profile", new { area = "Account" })">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li class="active"><a href="@Url.Action("Index", "Dashboard", new { area = "Account" })">Dashboard</a></li>
                    <li><a href="@Url.Action("Index", "ClientEvents", new { area = "Account" })">My Client Connections</a></li>
                    @if (Helpers.IsUserAdmin())
                    {
                        <li><a href="@Url.Action("Client", "Events", new { area = "Manage" })">All Client Connections</a></li>
                        <li><a href="@Url.Action("Server", "Events", new { area = "Manage" })">Server Events</a></li>
                        <li><a href="@Url.Action("Index", "Users", new {area = "Manage"})">Users</a></li>
                    }
                </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <h1 class="page-header">@ViewBag.Title</h1>
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @*<script src="../../assets/js/docs.min.js"></script>*@
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="~/Scripts/ie10-viewport-bug-workaround.js"></script>
    <script src="~/Scripts/mustache.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>